# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sageshop-app"
client_id = "d504750fbc91ff2443dedeebadc103cc"
application_url = "https://beans-capture-permalink-ca.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://beans-capture-permalink-ca.trycloudflare.com/auth/callback",
  "https://beans-capture-permalink-ca.trycloudflare.com/auth/shopify/callback",
  "https://beans-capture-permalink-ca.trycloudflare.com/api/auth/callback",
  "https://beans-capture-permalink-ca.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "k-jeans.myshopify.com"
